spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose-prod.yml

# MySql DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# wss autoconfigure
# secure (wss) enabled 'true' by default.  for non-secure (ws), change below value to 'false'
server.ssl.enabled=true
server.port=5555

# prod deployments should replace below self-signed certificate example with a valid certification
#server.ssl.bundle=server
#spring.ssl.bundle.jks.server.key.alias=localhost
#spring.ssl.bundle.jks.server.keystore.location=classpath:localhost.p12
#spring.ssl.bundle.jks.server.keystore.password=changeit
#spring.ssl.bundle.jks.server.keystore.type=PKCS12