plugins {
  id 'superconductor.java-conventions'
}

dependencies {
//  testImplementation project(':superconductor-lib-redis')
  testImplementation project(':superconductor-autoconfigure-redis')
  api project(':superconductor-autoconfigure-base')

  annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure'
  
  def subdivisionsVersion = '1.4.1'
  testImplementation 'com.prosilion:subdivisions:' + subdivisionsVersion

//  runtimeOnly('org.springframework.boot:spring-boot-starter-data-redis-reactive')
  api('org.springframework.boot:spring-boot-starter-data-redis-reactive:3.5.6')
  annotationProcessor('org.springframework.boot:spring-boot-starter-data-redis-reactive:3.5.6')

  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-configuration-processor'

  def springBootEmbeddedRedis = '1.0.1'
  testImplementation('io.github.tobi-laa:spring-boot-embedded-redis:' + springBootEmbeddedRedis)
  testImplementation('io.projectreactor:reactor-test:3.8.4')

  developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

  testImplementation 'org.springframework.boot:spring-boot-testcontainers'
  def testcontainers = '1.21.3'
  testImplementation "org.testcontainers:testcontainers:" + testcontainers
  testImplementation 'org.testcontainers:junit-jupiter:' + testcontainers

  testImplementation project(':test-common')
}

tasks.named('integrationTest') {
  mustRunAfter tasks.named('test')
}

tasks.named('integrationTestDocker') {
  mustRunAfter tasks.named('test')
}
