TEXT_NOTE=com.prosilion.nostr.event.TextNoteEvent
#RECOMMEND_SERVER=
#CONTACT_LIST=
#ENCRYPTED_DIRECT_MESSAGE=
#DELETION=
#REPOST=
#REACTION=
# handled by CacheBadgeAwardGenericEventService BADGE_AWARD_EVENT.BADGE_AWARD_VOTE=com.prosilion.nostr.event.BadgeAwardGenericEvent
# handled by BadgeAwardReputationEventService BADGE_AWARD_EVENT.BADGE_AWARD_REPUTATION=com.prosilion.nostr.event.BadgeAwardReputationEvent
#CHANNEL_CREATE=
#CHANNEL_METADATA=
#CHANNEL_MESSAGE=
#HIDE_MESSAGE=
#MUTE_USER=
#ENCRYPTED_PAYLOADS=
#OTS_EVENT=
#RESERVED_CASHU_WALLET_TOKENS=
#WALLET_UNSPENT_PROOF=
#WALLET_TX_HISTORY=
ZAP_REQUEST=com.prosilion.nostr.event.ZapRequestEvent
ZAP_RECEIPT=com.prosilion.nostr.event.ZapReceiptEvent
#REPLACEABLE_EVENT=
#PIN_LIST=
#RELAY_LIST_METADATA=
SEARCH_RELAYS_LIST=com.prosilion.nostr.event.SearchRelaysListEvent
#EPHEMERAL_EVENT=
#CLIENT_AUTH=
#STALL_CREATE_OR_UPDATE=
#PRODUCT_CREATE_OR_UPDATE=
#PRE_LONG_FORM_CONTENT=
# handled by CacheFollowSetsEventService FOLLOW_SETS=com.prosilion.nostr.event.FollowSetsEvent
# below previous intention as handled by CacheBadgeAwardRelaySetsEventService
RELAY_SETS=com.prosilion.nostr.event.RelaySetsEvent
#CURATION_SETS=
# below previous intention as handled by CacheFormulaEventService ARBITRARY_CUSTOM_APP_DATA=com.prosilion.nostr.event.FormulaEvent
#RELAY_DISCOVERY=
CLASSIFIED_LISTING_ACTIVE=com.prosilion.nostr.event.ClassifiedListingEvent
#CLASSIFIED_LISTING_INACTIVE=
#CLASSIFIED_LISTING_DRAFT=
CALENDAR_DATE_BASED_EVENT=com.prosilion.nostr.event.CalendarDateBasedEvent
CALENDAR_TIME_BASED_EVENT=com.prosilion.nostr.event.CalendarTimeBasedEvent
CALENDAR_RSVP_EVENT=com.prosilion.nostr.event.CalendarRsvpEvent
#BADGE_PROFILE_EVENT=
# handled by BadgeDefinitionGenericEventService BADGE_DEFINITION_EVENT.BADGE_DEFINITION_VOTE=com.prosilion.nostr.event.BadgeDefinitionGenericEvent
# handled by BadgeDefinitionReputationEventService BADGE_DEFINITION_EVENT.BADGE_DEFINITION_REPUTATION=com.prosilion.nostr.event.BadgeDefinitionReputationEvent
#WALLET=
#GROUP_ADMINS=
#GROUP_MEMBERS=
