services:
  superconductor-redis:
    container_name: superconductor-redis
    image: "redis:8.0.0"
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
  superconductor-app-redis:
    container_name: superconductor-app-redis
    image: superconductor-app-redis:1.16.0
    ports:
      - "5555:5555"
    links:
      - superconductor-redis
    environment:
      SPRING_PROFILES_ACTIVE: prod_ws
volumes:
  superconductor-redis:
    driver: local
