services:
  superconductor-db:
    container_name: superconductor-db-redis-dev_ws
    image: "redis:8.0.0"
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
  superconductor-app:
    container_name: superconductor-app-redis-dev_ws
    image: superconductor-app-redis:1.16.1
    ports:
      - "5555:5555"
    links:
      - superconductor-db
    environment:
      SPRING_PROFILES_ACTIVE: dev_ws
volumes:
  superconductor-db:
    driver: local
