services:
  superconductor-db:
    container_name: superconductor-redis-db-local
    image: "redis:8.0.0"
    hostname: localhost
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
volumes:
  superconductor-db:
    driver: local
