services:
  superconductor-db-redis-local:
    container_name: superconductor-db-redis-local
    image: "redis:8.0.0"
    hostname: localhost
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
volumes:
  superconductor-db-redis-local:
    driver: local
