# multiple docker instances using this yml file require lines suffixed with -UNIQUE_NAME to be uniquely named between instances
services:
  superconductor-db-redis-prod-wss-UNIQUE_NAME:
    container_name: superconductor-db-redis-prod-wss-UNIQUE_NAME
    image: "redis:8.0.0"
    hostname: superconductor-db-redis-prod-wss-UNIQUE_NAME
    ports:
      - "6379:6379" # first port number must be unique
    environment:
      - "REDIS_ARGS=--appendonly yes"
  superconductor-app-redis-prod-wss-UNIQUE_NAME:
    container_name: superconductor-app-redis-prod-wss-UNIQUE_NAME
    image: superconductor-app-redis:1.17.2
    ports:
      - "5555:5555" # first port number must be unique
      - "443:443" # first port number must be unique
    links:
      - superconductor-db-redis-prod-wss-UNIQUE_NAME
    environment:
      SPRING_PROFILES_ACTIVE: prod_wss
volumes:
  superconductor-db-redis-prod-wss-UNIQUE_NAME:
    driver: local
