services:
  superconductor-redis:
    container_name: superconductor-redis
    image: "redis:8.0.0"
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - "REDIS_ARGS=--appendonly yes"
#    networks:
#      docker-network:
#    volumes:
#      - ./data:/data
  superconductor-app-redis:
    container_name: superconductor-app-redis
    image: superconductor-app-redis:1.15.1
    ports:
      - "5555:5555"
#      docker debug port, note: requires image re-build
#      - '5005:5005'
    links:
      - superconductor-redis
#    depends_on:
#      superconductor-redis:
#        condition: service_healthy
    environment:
#      docker VM debug option
#      _JAVA_OPTIONS: >
#        -Xdebug
#        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: dev_ws
#      SPRING_DATASOURCE_URL: jdbc:mysql://superconductor-mysqldb:3316/superconductor
##      set below spring datasource parameters and credentials as desired
#      SPRING_DATASOURCE_USERNAME: mysqluser
#      SPRING_DATASOURCE_PASSWORD: mysqluserpass
#    networks:
#      docker-network:
volumes:
  superconductor-redis:
    driver: local
#networks:
#  docker-network:
#    driver: bridge
