services:
  superconductor-db:
    container_name: superconductor-db-sqlite-dev_ws
    image: hibitdev/sqlite:latest
    ports:
      - "8191:8191"
    command: ["tail", "-f", "/dev/null"]  # seems hacky, confirm to remove
    networks:
      docker-network-sqlite-dev:
  superconductor-app:
    container_name: superconductor-app-sqlite-dev_ws
    image: superconductor-app-sqlite:1.17.1
    ports:
      - "5555:5555"
    links:
      - superconductor-db
    environment:
      SPRING_PROFILES_ACTIVE: dev_ws
      SPRING_DATASOURCE_URL: jdbc:sqlite://superconductor-db-sqlite-dev_ws:8191/superconductor
      #      set below spring datasource parameters and credentials as desired
      SPRING_DATASOURCE_USERNAME: sqliteuser
      SPRING_DATASOURCE_PASSWORD: sqliteuserpass
    networks:
      docker-network-sqlite-dev:
volumes:
  superconductor-db:
    driver: local
networks:
  docker-network-sqlite-dev:
    driver: bridge
